<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class departemenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $departemen =[
            //regional 3
            [
                'divisi_id' => '1',
                'departemen' => 'Departemen Hukum dan Hubungan Masyarakat',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '1',
                'departemen' => 'Departemen Pengadaan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '1',
                'departemen' => 'Departemen Umum',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '1',
                'departemen' => 'Departemen Pelayanan SDM',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '2',
                'departemen' => 'Departemen Pemasaran',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '2',
                'departemen' => 'Departemen Pengusahaan Properti',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen Pemeliharaan Fasilitas Pelabuhan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen Pemeliharaan Peralatan Pelabuhan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen Sistem Manajamen',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen Teknologi Informasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen PMO Peralatan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen PMO Bali Nusa Tenggara',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen PMO Jawa Tengah',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '3',
                'departemen' => 'Departemen PMO Kalimantan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '4',
                'departemen' => 'Departemen HSSE',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '4',
                'departemen' => 'Departemen Pelaporan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '4',
                'departemen' => 'Departemen Pelayanan Kapal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '4',
                'departemen' => 'Departemen Pelayanan Petikemas & Barang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '4',
                'departemen' => 'Departemen Pelayanan Ro-Ro & Penumpang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '5',
                'departemen' => 'Departemen Perbendaharaan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '5',
                'departemen' => 'Departemen Perpajakan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '5',
                'departemen' => 'Departemen Pusat Layanan Keuangan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '6',
                'departemen' => 'Departemen Akuntansi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '6',
                'departemen' => 'Departemen Anggaran',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '6',
                'departemen' => 'Departemen Aset Tetap',
                'created_at' => null,
                'updated_at' => null,
            ],
            //Sub regional jawa
            [
                'divisi_id' => '7',
                'departemen' => 'Deputi Manajer Perencanaan dan Pengendalian Jatim',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Deputi Manajer Perencanaan dan Pengendalian',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Deputi Manajer Pelayanan Pemanduan Jatim',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Deputi Manajer Pelayanan Pemanduan Jateng',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Supervisor Pelayanan Kapal Gresik',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Supervisor Pelayanan Kapal dan Rupa-Rupa Usaha Tanjung Wangi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '7',
                'departemen' => 'Supervisor Pelayanan Kapal dan Rupa-Rupa Usaha Tanjung Intan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '8',
                'departemen' => 'Deputi Manajer Pemasaran',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '8',
                'departemen' => 'Deputi Manajer Pelayanan Pelanggan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '9',
                'departemen' => 'Deputi Manajer Properti dan Rupa-Rupa Usaha Wilayah Jatim 1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '9',
                'departemen' => 'Deputi Manajer Properti dan Rupa-Rupa Usaha Wilayah Jatim 2',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '9',
                'departemen' => 'Deputi Manajer Properti dan Rupa-Rupa Usaha Wilayah Jateng',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '10',
                'departemen' => 'Deputi Manajer Perencanaan Fasilitas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '10',
                'departemen' => 'Deputi Manajer Pemeliharaan Fasilitas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '10',
                'departemen' => 'Deputi Manajer Teknik Jateng',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '10',
                'departemen' => 'Deputi Manajer Peralatan dan Instalasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '10',
                'departemen' => 'Supervisor Teknik Gresik',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '11',
                'departemen' => 'Deputi Manajer SDM dan Legal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '11',
                'departemen' => 'Deputi Manajer Umum dan Humas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '11',
                'departemen' => 'Deputi Manajer Health, Safety, Security, and Environment',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '12',
                'departemen' => 'Deputi Manajer Tanggung Jawab Sosial dan Lingkungan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '13',
                'departemen' => 'Deputi Manajer Manajemen Mutu dan Risiko',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '14',
                'departemen' => 'Deputi Manajer Teknologi Informasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '15',
                'departemen' => 'Manajer Pelayanan Terminal Area 1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '15',
                'departemen' => 'Manajer Pelayanan Terminal Area 2',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '15',
                'departemen' => 'Manajer Terminal Penumpang GSN dan Roro',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '16',
                'departemen' => 'Manajer Pelayanan Terminal Group A',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '16',
                'departemen' => 'Manajer Pelayanan Terminal Group B',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '16',
                'departemen' => 'Manajer Pelayanan Terminal Group C',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '16',
                'departemen' => 'Manajer Pelayanan Terminal Group D',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '17',
                'departemen' => 'General Manager Tanjung Tembaga',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '17',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '18',
                'departemen' => 'General Manager Kalianget',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '19',
                'departemen' => 'Manajer Pelayanan Terminal Group A',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '19',
                'departemen' => 'Manajer Pelayanan Terminal Group B',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '19',
                'departemen' => 'Manajer Pelayanan Terminal Group C',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '19',
                'departemen' => 'Manajer Pelayanan Terminal Group D',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '19',
                'departemen' => 'Manajer Terminal Penumpang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '20',
                'departemen' => 'General Manager Tegal',
                'created_at' => null,
                'updated_at' => null,
            ],
            //sub regional kalimantan
            [
                'divisi_id' => '21',
                'departemen' => 'Deputi Manajer Perencanaan, Pengendalian & Terminal Penumpang Bandarmasih',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '21',
                'departemen' => 'Deputi Manajer Pelayanan Pemanduan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '21',
                'departemen' => 'Supervisor Pelayanan Kapal Kotabaru',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '21',
                'departemen' => 'Supervisor Pelayanan Kapal Batulicin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '21',
                'departemen' => 'Supervisor Pelayanan Kapal Sampit & Bagendang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '21',
                'departemen' => 'Supervisor Pelayanan Kapal Kumai & Bumiharjo',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '22',
                'departemen' => 'Deputi Manajer Pemasaran dan Pelayanan Pelanggano',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '22',
                'departemen' => 'Deputi Manajer Properti dan Rupa-Rupa Usaha',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '22',
                'departemen' => 'Manajer Pelayanan Pelabuhan Kumai',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '22',
                'departemen' => 'Manajer Pelayanan Pelabuhan Sampit',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '23',
                'departemen' => 'Deputi Manajer Fasilitas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '23',
                'departemen' => 'Deputi Manajer Peralatan dan Instalasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '23',
                'departemen' => 'Supervisor Teknik Kotabaru',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '23',
                'departemen' => 'Supervisor Teknik Batulicin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '24',
                'departemen' => 'Deputi Manajer SDM dan Legal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '24',
                'departemen' => 'Deputi Manajer Umum Humas dan TJSL',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '24',
                'departemen' => 'Deputi Manajer Health, Safety, Security, and Environment',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '25',
                'departemen' => 'Deputi Manajer Akuntansi Keuangan dan Manajemen',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '25',
                'departemen' => 'Deputi Manajer Pembendaharaan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '26',
                'departemen' => 'Deputi Manajemen Mutu dan Risiko',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '27',
                'departemen' => 'Deputi Manajer Teknologi Informasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '28',
                'departemen' => 'General Manager Kotabaru',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '28',
                'departemen' => 'Manajer Pelayanan Terminal Kotabaru',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '29',
                'departemen' => 'General Manager Pulang Pisau',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '30',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '30',
                'departemen' => 'Supervisor Terminal Satui',
                'created_at' => null,
                'updated_at' => null,
            ],
            //sub regional bali nusra
            [
                'divisi_id' => '31',
                'departemen' => 'Deputi Manajer Perencanaan dan Pengendalian',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '31',
                'departemen' => 'Deputi Manajer Pelayanan Pemanduan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '31',
                'departemen' => 'Supervisor Pelayanan Kapal dan Non Petikemas Tenau Kupang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '31',
                'departemen' => 'Supervisor Pelayanan Kapal Lembar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '32',
                'departemen' => 'Deputi Manajer Pemasaran dan Pelayanan Pelanggan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '32',
                'departemen' => 'Deputi Manajer Properti dan Rupa-Rupa Usaha',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Deputi Manajer Fasilitas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Deputi Manajer Peralatan dan Instalasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Supervisor Teknik Tenau Kupang & Kalabahi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Supervisor Teknik Waingapu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Supervisor Teknik Maumere & Ende-Ippi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Supervisor Teknik Lembar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '33',
                'departemen' => 'Supervisor Teknik Bima & Badas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '34',
                'departemen' => 'Deputi Manajer Sumber Daya Manusia dan Legal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '34',
                'departemen' => 'Deputi Manajer Umum dan Humas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '34',
                'departemen' => 'Deputi Manajer Health, Safety, Security, and Environment',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '35',
                'departemen' => 'Deputi Manajer Akuntansi Keuangan dan Manajemen',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '35',
                'departemen' => 'Deputi Manajer Pembendaharaan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '36',
                'departemen' => 'Deputi Manajer Tanggung Jawab Sosial dan Lingkungan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '37',
                'departemen' => 'Deputi Manajer Mutu dan Risiko',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '38',
                'departemen' => 'Deputi Manajer Teknologi Informasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '39',
                'departemen' => 'General Manager Benoa',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '39',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '40',
                'departemen' => 'General Manager Lembar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '40',
                'departemen' => 'Manajer Pelayanan Petikemas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '40',
                'departemen' => 'Manajer Pelayanan Non Petikemas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '41',
                'departemen' => 'General Manager Bima',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '41',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '42',
                'departemen' => 'General Manager Celukan Bawang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '42',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '43',
                'departemen' => 'General Manager Maumere',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '43',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '44',
                'departemen' => 'General Manager Ende-Ippi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '45',
                'departemen' => 'General Manager Waingapu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '45',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '46',
                'departemen' => 'General Manager Kalabahi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '47',
                'departemen' => 'General Manager Badas',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '47',
                'departemen' => 'Manajer Pelayanan Terminal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'divisi_id' => '48',
                'departemen' => 'General Manager Labuan Bajo',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        DB::table('departemen')->insert($departemen);
    }
}
